services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: plataforma_db
      POSTGRES_USER: plataforma_user
      POSTGRES_PASSWORD: plataforma_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=plataforma_db
      - DB_USER=plataforma_user
      - DB_PASSWORD=plataforma_pass
      - DB_HOST=db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
